#ifndef	__guiDllApi_H__
#define	__guiDllApi_H__ "Generated by make system" 

#ifdef	__WINDOWS
# ifdef	gui_EXPORTS
#  define gui_API __declspec(dllexport)
# else
#  define gui_API __declspec(dllimport)
# endif
#else
# define gui_API
#endif

#endif /* __guiDllApi_H__ */
