#ifndef	__hdf5sshDllApi_H__
#define	__hdf5sshDllApi_H__ "Generated by make system" 

#ifdef	__WINDOWS
# ifdef	hdf5ssh_EXPORTS
#  define hdf5ssh_API __declspec(dllexport)
# else
#  define hdf5ssh_API __declspec(dllimport)
# endif
#else
# define hdf5ssh_API
#endif

#endif /* __hdf5sshDllApi_H__ */
