#ifndef	__hdf5toolsDllApi_H__
#define	__hdf5toolsDllApi_H__ "Generated by make system" 

#ifdef	__WINDOWS
# ifdef	hdf5tools_EXPORTS
#  define hdf5tools_API __declspec(dllexport)
# else
#  define hdf5tools_API __declspec(dllimport)
# endif
#else
# define hdf5tools_API
#endif

#endif /* __DllApi_H__ */
